'use server';
/**
 * @fileOverview This file defines a Genkit flow for automatically tagging images
 * uploaded to the gallery using the Google Cloud Vision API.
 *
 * - imageTagging - A function that triggers the image tagging flow.
 * - ImageTaggingInput - The input type for the imageTagging function.
 * - ImageTaggingOutput - The return type for the imageTagging function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImageTaggingInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to be tagged, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ImageTaggingInput = z.infer<typeof ImageTaggingInputSchema>;

const ImageTaggingOutputSchema = z.object({
  tags: z.array(z.string()).describe('An array of tags generated by the Vision API.'),
});
export type ImageTaggingOutput = z.infer<typeof ImageTaggingOutputSchema>;

export async function imageTagging(input: ImageTaggingInput): Promise<ImageTaggingOutput> {
  return imageTaggingFlow(input);
}

const imageTaggingPrompt = ai.definePrompt({
  name: 'imageTaggingPrompt',
  input: {schema: ImageTaggingInputSchema},
  output: {schema: ImageTaggingOutputSchema},
  prompt: `You are an AI that analyzes images and returns relevant tags.

  Analyze the following image and generate a list of tags that describe its content.
  The tags should be relevant and concise.

  Image: {{media url=photoDataUri}}
  `, // Added Handlebars media helper.
});

const imageTaggingFlow = ai.defineFlow(
  {
    name: 'imageTaggingFlow',
    inputSchema: ImageTaggingInputSchema,
    outputSchema: ImageTaggingOutputSchema,
  },
  async input => {
    const {output} = await imageTaggingPrompt(input);
    return output!;
  }
);
